Metrics/LineLength:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Layout/SpaceInsideBrackets:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Lint/BlockAlignment:
  Exclude:
    - 'spec/**/*'
    